### ISSUE TITLE
گرفتن اطلاعات از فروشگاه

### ISSUE THREAD

**Issue by WhiteWolf-Sim** [ygngy/godot-android-billing-ir#2]
سلام چطور میشه اطلاعاتی مثل قیمت (price) رو از فروشگاه گرفت ؟
p.price?
p(price)?
p[price]?
.......

**Comment by ygngy** [comment]
اگر به صورت توضیحات readme عمل کنید
پارامتر این تابع آرایه‌ای از کالاهایی است که در فروشگاه مایکت یا بازار تعریف کرده‌اید
پارامتر این تابع آرایه است چون بیش از یک کالا میتوان تعریف کرد
به صورت کد زیر یک حلقه تعریف کنید و قیمت و آیدی هر کدام از کالاها را در آن بدست آورید
```
func _on_QuerySucceed(results):
	# اطلاعات کالاها در پارامتر این تابع دریافت می‌شود
	# پارامتر این تابع آرایه‌ای از دیکشنری‌ها است کلیدهای هر دیکشنری به صورت زیر است
	# "product_id", "type", "price", "title", "description"
	for kala in results:
		var price = kala["price"]
                var id = kala["product_id"]
```
